### ISSUE TITLE
VMD plugin does not install

### ISSUE THREAD

**Issue by MuhammadIIsmail** [sfernando-BAEN/ELIXIR-A#1]
I have followed the steps for installing the VMD plugin, but its tab does not appear under Extensions-Modeling.

**Comment by sfernando-BAEN** [comment]
Hello Muhammad,

Thanks for your interest in our program. By copying I am requesting Dr. Haoqi Wang, who is the developer of the algorithm to respond when he can find some time.

We will try to address this issue in the steps.

Best Regards, San

Sandun (San) Fernando, Ph.D., P.E.
Professor and Associate Department Head for Graduate Programs and Research
Biological and Agricultural Engineering Department
303C Scoates Hall
2117 TAMU
Texas A&M University
College Station, TX  77843-2117
Tel: 979-845-9793 ;  fax 979-845-3081
Email: ***@***.******@***.***>

From: Muhammad I. Ismail ***@***.***>
Sent: Monday, October 24, 2022 8:51 AM
To: sfernando-BAEN/ELIXIR-A ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sfernando-BAEN/ELIXIR-A] VMD plugin does not install (Issue #1)

I have followed the steps for installing the VMD plugin, but its tab does not appear under Extensions-Modeling. - Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

I have followed the steps for installing the VMD plugin, but its tab does not appear under Extensions-Modeling.

-

**Comment by Curiouss** [comment]
Hi Muhammad,

Please try again with the following steps.

1. Download the EXLIXIR-A package from the link below.
https://github.com/sfernando-BAEN/ELIXIR-A/releases/tag/v2.0

2. unzip the file and copy the elixir2.0 folder to VMD TCL plugins directory $VMD/plugins/noarch/tcl/
if your vmd folder is /user/home/VMD, then TCL plugins directory will be /user/home/VMD/plugins/noarch/tcl/

3. Add the command in file /scripts/vmd/loadplugin.tcl.4. 
if your vmd folder is /user/home/VMD, then file path will be /user/home/VMD/scripts/vmd/loadplugin.tcl

Under  line 
```sh
### Modeling menu 
```
Add 
```sh
vmd_install_extension elixir elixir_tk  "Modeling/ELIXIR-A"
```

4. Open VMD.

If this doesn't work for you, please send us the screenshot of your Command Prompt (Windows) or Terminal (Mac/Linux). 

Thanks,
Haoqi

**Comment by MuhammadIIsmail** [comment]
Thank you, Professor Fernando for your reply. I solved my problem. I was using the wrong VMD directory for installation. I recommend adding a command in the installation guide to determine the VMD directory like: **global env; puts $env(VMDDIR)** in the VMD Tk Console.
